"""
하위 호환성을 위해 유지되는 래퍼(Wrapper) 모듈입니다.
리팩토링된 신규 모듈(database, utils.text_processor, utils.classifier)의 주요 함수 및 상수를 다시 노출합니다.
"""
from database import DB_NAME, create_student, init_db, save_activity
from utils.classifier import (
    ACTIVITY_CATEGORIES,
    CATEGORY_RULES,
    FIELD_KEYWORDS,
    INTEREST_CATEGORIES,
    NOISE_BOARD_CATEGORIES,
    NOISE_KEYWORDS,
    STAFF_HIRING_KEYWORDS,
    classify_activity_category,
    classify_campus_scope,
    classify_interest_categories,
    is_noise_notice,
    is_staff_hiring_notice,
    strip_title_noise,
)
from utils.text_processor import (
    DATE_PATTERN,
    DEADLINE_LABELS,
    KST,
    NEXT_LABELS,
    PERIOD_LABELS,
    TARGET_LABELS,
    clean_text,
    compact_text,
    compute_dday,
    extract_deadline_date,
    extract_target_text,
    is_recent_upload,
    normalize_date,
    normalize_target,
    now_kst_string,
    today_kst,
)

__all__ = [
    "DB_NAME",
    "KST",
    "ACTIVITY_CATEGORIES",
    "INTEREST_CATEGORIES",
    "FIELD_KEYWORDS",
    "TARGET_LABELS",
    "NEXT_LABELS",
    "DATE_PATTERN",
    "DEADLINE_LABELS",
    "PERIOD_LABELS",
    "STAFF_HIRING_KEYWORDS",
    "NOISE_KEYWORDS",
    "NOISE_BOARD_CATEGORIES",
    "CATEGORY_RULES",
    "strip_title_noise",
    "is_noise_notice",
    "clean_text",
    "compact_text",
    "today_kst",
    "now_kst_string",
    "normalize_date",
    "is_recent_upload",
    "extract_deadline_date",
    "compute_dday",
    "classify_activity_category",
    "is_staff_hiring_notice",
    "classify_campus_scope",
    "classify_interest_categories",
    "extract_target_text",
    "normalize_target",
    "init_db",
    "create_student",
    "save_activity",
]
